Tree.destroy_all
Tree.destroy_all

guest = User.create(user_name: "Guest")


blue_spruce = Tree.create(common_name: "Blue Spruce", 
                    common_fam_name: "Pine", 
                    coniferous_deciduous: "Coniferous", 
                    sci_name: "Picea pungens", 
                    bark_color: "gray-brown",
                    bark_texture: "Furrowed",
                    leaf_type: "Needle",
                    leaf_arrangement:"none",
                    leaf_shape:"none",
                    needle_shape: "Sharp",
                    cone_type: "Woody",
                    fruit: "Cone",
                    min_elevation: 6700,
                    max_elevation: 11500,
                    min_height: 70,
                    max_height: 115,
                    twig_texture: "Smooth",
                    flower_shape:"none",
                    flower_color:"none",
                    habitat: "foothills/montane",
                    leaf_picture: "imgcat ./lib/pic/blue-spruce-leaftall.jpg",
                    tree_picture: "imgcat ./lib/pic/blue-spruce-tree.jpg"
                    )         

blue_spruce2 = Tree.create(common_name: "Blue Sprucey", 
                    common_fam_name: "Pine", 
                    coniferous_deciduous: "Coniferous", 
                    sci_name: "Picea pungens", 
                    bark_color: "gray-brown",
                    bark_texture: "Furrowed",
                    leaf_type: "Needle",
                    leaf_arrangement:"none",
                    leaf_shape:"none",
                    needle_shape: "Sharp",
                    cone_type: "Woody",
                    fruit: "Cone",
                    min_elevation: 6700,
                    max_elevation: 11500,
                    min_height: 70,
                    max_height: 115,
                    twig_texture: "Rough",
                    flower_shape:"none",
                    flower_color:"none",
                    habitat: "foothills/montane",
                    leaf_picture: "imgcat ./lib/pic/blue-spruce-leaftall.jpg",
                    tree_picture: "imgcat ./lib/pic/blue-spruce-tree.jpg"
                    )                       
                    
boxelder = Tree.create(common_name: "Boxelder", 
                    common_fam_name: "Maple", 
                    coniferous_deciduous: "Coniferous", 
                    sci_name: "Acer negundo", 
                    bark_color: "gray-brown",
                    bark_texture: "Furrowed",
                    leaf_type: "Leaf",
                    leaf_arrangement: "Opposite",
                    leaf_shape: "Pinnate",
                    needle_shape:"none",
                    cone_type:"none",
                    fruit: "Samara",
                    min_elevation: 4000,
                    max_elevation: 10000,
                    min_height: 5,
                    max_height: 35,
                    twig_texture: "Smooth",
                    flower_shape: "Inconspicuous",
                    flower_color: "Green",
                    habitat: "plains/foothills",
                    leaf_picture: "imgcat ./lib/pic/BoxelderLeaves-225x300.jpg",
                    tree_picture: "imgcat ./lib/pic/BoxelderTree.jpg"
                    )        
                    
bristlecone_pine = Tree.create(common_name: "Bristlecone Pine", 
                    common_fam_name: "Pine", 
                    coniferous_deciduous: "Coniferous", 
                    sci_name: "Pinus aristata", 
                    bark_color: "red-brown",
                    bark_texture: "Furrowed",
                    leaf_type: "Needle",
                    leaf_arrangement:"none",
                    leaf_shape:"none",
                    needle_shape: "Clusters of 5",
                    cone_type: "Woody",
                    fruit: "Cone",
                    min_elevation: 9200,
                    max_elevation: 11800,
                    min_height: 15,
                    max_height: 30,
                    twig_texture: "Smooth",
                    flower_shape:"none",
                    flower_color:"none",
                    habitat: "montane/subalpine",
                    leaf_picture: "imgcat ./lib/pic/Bristlecone-leaf.jpg",
                    tree_picture: "imgcat ./lib/pic/Bristlecone-tree.jpg"
                    )       
                    
chokecherry = Tree.create(common_name: "Chokecherry", 
                    common_fam_name: "Rose", 
                    coniferous_deciduous: "Deciduous", 
                    sci_name: "Prunus virginiana", 
                    bark_color: "red-brown",
                    bark_texture: "Bumpy",
                    leaf_type: "Leaf",
                    leaf_arrangement: "Alternate",
                    leaf_shape: "Oblanceolate",
                    needle_shape:"none",
                    cone_type:"none",
                    fruit: "Fleshy",
                    min_elevation: 5000,
                    max_elevation: 10000,
                    min_height: 10,
                    max_height: 15,
                    twig_texture: "Smooth",
                    flower_shape: "Star or Cross Shaped",
                    flower_color: "White",
                    habitat: "plains/foothills",
                   leaf_picture: "imgcat ./lib/pic/ChokecherrydrupesLeaves.jpg",
                    tree_picture: "imgcat ./lib/pic/ChokecherryTree.jpg" 
                    )     
chokecherry2 = Tree.create(common_name: "Chokecherry Tree", 
                    common_fam_name: "Rose", 
                    coniferous_deciduous: "Deciduous", 
                    sci_name: "Prunus virginiana", 
                    bark_color: "red-brown",
                    bark_texture: "Bumpy",
                    leaf_type: "Leaf",
                    leaf_arrangement: "Alternate",
                    leaf_shape: "Oblanceolate",
                    needle_shape:"none",
                    cone_type:"none",
                    fruit: "Fleshy",
                    min_elevation: 5000,
                    max_elevation: 10000,
                    min_height: 10,
                    max_height: 15,
                    twig_texture: "Smooth",
                    flower_shape: "Star or Cross Shaped",
                    flower_color: "Green",
                    habitat: "plains/foothills",
                    leaf_picture: "imgcat ./lib/pic/ChokecherrydrupesLeaves.jpg",
                    tree_picture: "imgcat ./lib/pic/ChokecherryTree.jpg" 
                    )                         

douglas_fur = Tree.create(common_name: "Douglas Fir", 
                    common_fam_name: "Pine", 
                    coniferous_deciduous: "Coniferous", 
                    sci_name: "Pseudotsuga menziesii", 
                    bark_color: "red-brown",
                    bark_texture: "Furrowed",
                    leaf_type: "Needle",
                    leaf_arrangement:"none",
                    leaf_shape:"none",
                    needle_shape: "Flat",
                    cone_type: "Papery",
                    fruit: "Cone",
                    min_elevation: 6000,
                    max_elevation: 9500,
                    min_height: 100,
                    max_height: 130,
                    twig_texture: "Rough",
                    flower_shape:"none",
                    flower_color:"none",
                    habitat: "foothills/montane",
                    leaf_picture: "imgcat ./lib/pic/Doug-Fir-cone.jpg",
                    tree_picture: "imgcat ./lib/pic/Douglas-fir-treerevised.jpg"   
                    )   
                    
engelmann_spruce = Tree.create(common_name: "Engelmann Spruce", 
                    common_fam_name: "Pine", 
                    coniferous_deciduous: "Coniferous", 
                    sci_name: "Picea engelmannii", 
                    bark_color: "gray-brown",
                    bark_texture: "Scaled",
                    leaf_type: "Needle",
                    leaf_arrangement:"none",
                    leaf_shape:"none",
                    needle_shape: "Sharp",
                    cone_type: "Woody",
                    fruit: "Cone",
                    min_elevation: 8000,
                    max_elevation: 11000,
                    min_height: 45,
                    max_height: 130,
                    twig_texture: "Hairy",
                    flower_shape:"none",
                    flower_color:"none",
                    habitat: "montane/subalpine",
                    leaf_picture: "imgcat ./lib/pic/Eng-Spruce-leaf.jpg",
                    tree_picture: "imgcat ./lib/pic/Eng-Spruce-tree.jpg" 
                    )     

gambel_oak = Tree.create(common_name: "Gambel Oak", 
                    common_fam_name: "Oak", 
                    coniferous_deciduous: "Deciduous", 
                    sci_name: "Quercus gambelii", 
                    bark_color: "gray-brown",
                    bark_texture: "Scaled",
                    leaf_type: "Leaf",
                    leaf_arrangement: "Alternate",
                    leaf_shape: "Lobed",
                    needle_shape:"none",
                    cone_type:"none",
                    fruit: "Acorn",
                    min_elevation: 4000,
                    max_elevation: 8500,
                    min_height: 10,
                    max_height: 15,
                    twig_texture: "Smooth",
                    flower_shape: "Inconspicuous",
                    flower_color: "Green",
                    habitat: "foothills",
                    leaf_picture: "imgcat ./lib/pic/GambelOakLeavestall-225x300.jpg",
                    tree_picture: "imgcat ./lib/pic/GambelOak.jpg" 
                    )     

limber_pine = Tree.create(common_name: "Limber Pine", 
                    common_fam_name: "Pine", 
                    coniferous_deciduous: "Coniferous", 
                    sci_name: "Pinus flexilis", 
                    bark_color: "brown",
                    bark_texture: "Furrowed",
                    leaf_type: "Needle",
                    leaf_arrangement:"none",
                    leaf_shape:"none",
                    needle_shape: "Clusters of 5",
                    cone_type: "Woody",
                    fruit: "Cone",
                    min_elevation: 5000,
                    max_elevation: 12000,
                    min_height: 40,
                    max_height: 50,
                    twig_texture: "Smooth",
                    flower_shape:"none",
                    flower_color:"none",
                    habitat: "montane/subalpine",
                    leaf_picture: "imgcat ./lib/pic/Limber-leaf.jpg",
                    tree_picture: "imgcat ./lib/pic/Limber-tree.jpg" 
                )     

lodgepole_pine = Tree.create(common_name: "Lodgepole Pine", 
                    common_fam_name: "Pine", 
                    coniferous_deciduous: "Coniferous", 
                    sci_name: "Pinus contorta", 
                    bark_color: "brown",
                    bark_texture: "Scaled",
                    leaf_type: "Needle",
                    leaf_arrangement:"none",
                    leaf_shape:"none",
                    needle_shape: "Clusters of 2-3",
                    cone_type: "Woody",
                    fruit: "Cone",
                    min_elevation: 6000,
                    max_elevation: 11000,
                    min_height: 20,
                    max_height: 80,
                    twig_texture: "Smooth",
                    flower_shape:"none",
                    flower_color:"none",
                    habitat: "montane/subalpine",
                   leaf_picture: "imgcat ./lib/pic/Lodgepole-Leaftall-225x300.jpg",
                    tree_picture: "imgcat ./lib/pic/lodgepole-tree2.jpg" 
                )     

narrowleaf_cottonwood = Tree.create(common_name: "Narrowleaf Cottonwood", 
                    common_fam_name: "Willow", 
                    coniferous_deciduous: "Deciduous", 
                    sci_name: "Populus angustifolia", 
                    bark_color: "gray-brown",
                    bark_texture: "Furrowed",
                    leaf_type: "Leaf",
                    leaf_arrangement: "Alternate",
                    leaf_shape: "Narrow",
                    needle_shape:"none",
                    cone_type:"none",
                    fruit: "Capsule",
                    min_elevation: 5000,
                    max_elevation: 8000,
                    min_height: 30,
                    max_height: 60,
                    twig_texture: "Smooth",
                    flower_shape: "Inconspicuous",
                    flower_color: "Red",
                    habitat: "foothills/montane",
                    leaf_picture: "imgcat ./lib/pic/Narrow-Cotton-leaftall-225x300.jpg",
                    tree_picture: "imgcat ./lib/pic/Narrow-Cotton-tree.jpg"  
                )    
                    
                    
peachleaf_willow = Tree.create(common_name: "Peachleaf Willow", 
                    common_fam_name: "Willow", 
                    coniferous_deciduous: "Deciduous", 
                    sci_name: "Salix amygdaloides", 
                    bark_color: "red-brown",
                    bark_texture: "Smooth",
                    leaf_type: "Leaf",
                    leaf_arrangement: "Alternate",
                    leaf_shape: "Narrow",
                    needle_shape:"none",
                    cone_type:"none",
                    fruit: "Capsule",
                    min_elevation: 3500,
                    max_elevation: 7500,
                    min_height: 10,
                    max_height: 40,
                    twig_texture: "Smooth",
                    flower_shape: "Inconspicuous",
                    flower_color: "Yellow",
                    habitat: "foothills/montane",
                    leaf_picture: "imgcat ./lib/pic/PeachleafWillowLeaves-225x300.jpg",
                    tree_picture: "imgcat ./lib/pic/PeachleafWillowTree.jpg"
                )         
                    
pinyon_pine = Tree.create(common_name: "Pinyon Pine", 
                    common_fam_name: "Pine", 
                    coniferous_deciduous: "Coniferous", 
                    sci_name: "Pinus edulis", 
                    bark_color: "red-brown",
                    bark_texture: "Furrowed",
                    leaf_type: "Needle",
                    leaf_arrangement:"none",
                    leaf_shape:"none",
                    needle_shape:"Clusters of 5",
                    cone_type:"Woody",
                    fruit: "Cone",
                    min_elevation: 5200,
                    max_elevation: 9000,
                    min_height: 20,
                    max_height: 50,
                    twig_texture: "Rough",
                    flower_shape:"none",
                    flower_color:"none",
                    habitat: "foothills/montane",
                    leaf_picture: "imgcat ./lib/pic/pinon-leaftall-225x300.jpg",
                    tree_picture: "imgcat ./lib/pic/pinon-tree.jpg"
                )        
                    
plains_cottonwood = Tree.create(common_name: "Plains Cottonwood", 
                    common_fam_name: "Willow", 
                    coniferous_deciduous: "Deciduous", 
                    sci_name: "Populus deltoides",
                    bark_color: "gray",
                    bark_texture: "Furrowed",
                    leaf_type: "Leaf",
                    leaf_arrangement: "Alternate",
                    leaf_shape: "Deltoid",
                    needle_shape:"none",
                    cone_type:"none",
                    fruit: "Capsule",
                    min_elevation: 3500,
                    max_elevation: 6500,
                    min_height: 36,
                    max_height: 190,
                    twig_texture: "Smooth",
                    flower_shape: "Inconspicuous",
                    flower_color: "Red",
                    habitat: "lower river valleys",
                    leaf_picture: "imgcat ./lib/pic/Plains-Cotton-leaf.jpg",
                    tree_picture: "imgcat ./lib/pic/Plains-Cotton-tree.jpg"
                )       
                    
ponderosa_pine = Tree.create(common_name: "Ponderosa Pine", 
                    common_fam_name: "Pine", 
                    coniferous_deciduous: "Coniferous", 
                    sci_name: "Pinus ponderosa", 
                    bark_color: "red-brown",
                    bark_texture: "Furrowed",
                    leaf_type: "Needle",
                    leaf_arrangement:"none",
                    leaf_shape:"none",
                    needle_shape: "Clusters of 2-3",
                    cone_type: "Woody",
                    fruit: "Cone",
                    min_elevation: 6300,
                    max_elevation: 9500,
                    min_height: 40,
                    max_height: 160,
                    twig_texture: "Rough",
                    flower_shape:"none",
                    flower_color:"none",
                    habitat: "foothills/montane",
                    leaf_picture: "imgcat ./lib/pic/Ponderosa-Leaftall-225x300.jpg",
                    tree_picture: "imgcat ./lib/pic/ponderosa-tree-modern.jpg" 
                )     

quaking_aspen = Tree.create(common_name: "Quaking Aspen", 
                    common_fam_name: "Willow", 
                    coniferous_deciduous: "Deciduous", 
                    sci_name: "Populs tremuloides", 
                    bark_color: "gray",
                    bark_texture: "Smooth",
                    leaf_type: "Leaf",
                    leaf_arrangement: "Alternate",
                    leaf_shape: "Orbicular",
                    needle_shape:"none",
                    cone_type:"none",
                    fruit: "Capsule",
                    min_elevation: 6500,
                    max_elevation: 11500,
                    min_height: 35,
                    max_height: 50,
                    twig_texture: "Smooth",
                    flower_shape: "Inconspicuous",
                    flower_color: "White",
                    habitat: "foothills/montane",
                    leaf_picture: "imgcat ./lib/pic/Aspen-trees-path.jpg",
                    tree_picture: "imgcat ./lib/pic/Aspen-trees-path.jpg"   
                )   
                    
rocky_mountain_maple = Tree.create(common_name: "Rocky Mountain Maple", 
                    common_fam_name: "Maple", 
                    coniferous_deciduous: "Deciduous", 
                    sci_name: "Acer glabrum", 
                    bark_color: "gray-brown",
                    bark_texture: "Smooth",
                    leaf_type: "Leaf",
                    leaf_arrangement: "Opposite",
                    leaf_shape: "Palmate",
                    needle_shape:"none",
                    cone_type:"none",
                    fruit: "Samara",
                    min_elevation: 3000,
                    max_elevation: 10000,
                    min_height: 20,
                    max_height: 30,
                    twig_texture: "Smooth",
                    flower_shape: "Other",
                    flower_color: "Yellow",
                    habitat: "foothills/montane",
                    leaf_picture: "imgcat ./lib/pic/MountainMapleLeavesPendant.jpg",
                    tree_picture: "imgcat ./lib/pic/MountainMapleTree.jpg" 
                )     

rocky_mountain_juniper = Tree.create(common_name: "Rocky Mountan Juniper", 
                    common_fam_name: "Cypress", 
                    coniferous_deciduous: "Coniferous", 
                    sci_name: "Juniperus scopulorum", 
                    bark_color: "gray-brown",
                    bark_texture: "Scaled",
                    leaf_type: "Needle",
                    leaf_arrangement:"none",
                    leaf_shape:"none",
                    needle_shape: "Scaled",
                    cone_type: "Berry",
                    fruit: "Cone",
                    min_elevation: 5000,
                    max_elevation: 9000,
                    min_height: 20,
                    max_height: 50,
                    twig_texture: "Peeling",
                    flower_shape:"none",
                    flower_color:"none",
                    habitat: "foothills/montane",
                    leaf_picture: "imgcat ./lib/pic/RMJuniper-leaf.jpg",
                    tree_picture: "imgcat ./lib/pic/RMJuniper-tree.jpg" 
                )     

subalpine_fir = Tree.create(common_name: "Subalpine Fir", 
                    common_fam_name: "Pine", 
                    coniferous_deciduous: "Coniferous", 
                    sci_name: "Abies lasiocarpa", 
                    bark_color: "gray-brown",
                    bark_texture: "Furrowed",
                    leaf_type: "Needle",
                    leaf_arrangement:"none",
                    leaf_shape:"none",
                    needle_shape: "Flat",
                    cone_type: "Woody",
                    fruit: "Cone",
                    min_elevation: 8000,
                    max_elevation: 12000,
                    min_height: 60,
                    max_height: 100,
                    twig_texture: "Smooth",
                    flower_shape:"none",
                    flower_color:"none",
                    habitat: "montane/subalpine",
                    leaf_picture: "imgcat ./lib/pic/SubFir-leaftall.jpg",
                    tree_picture: "imgcat ./lib/pic/Subalpine-fir-tree2.jpg" 
                )     

thinleaf_alder = Tree.create(common_name: "Thinleaf Alder", 
                    common_fam_name: "Birch", 
                    coniferous_deciduous: "Deciduous", 
                    sci_name: "Alnus tenuifolia", 
                    bark_color: "gray-brown",
                    bark_texture: "Bumpy",
                    leaf_type: "Leaf",
                    leaf_arrangement: "Alternate",
                    leaf_shape: "Orbicular",
                    needle_shape:"none",
                    cone_type:"none",
                    fruit: "Samara",
                    min_elevation: 5000,
                    max_elevation: 10000,
                    min_height: 15,
                    max_height: 40,
                    twig_texture: "Smooth",
                    flower_shape: "Inconspicuous",
                    flower_color: "Red",
                    habitat: "montane",
                    leaf_picture: "imgcat ./lib/pic/AlderLeaves.jpg",
                    tree_picture: "imgcat ./lib/pic/AlderTree.jpg" 
                )     

white_fir = Tree.create(common_name: "White Fir", 
                    common_fam_name: "Pine", 
                    coniferous_deciduous: "Coniferous", 
                    sci_name: "Abies concolor", 
                    bark_color: "gray",
                    bark_texture: "Furrowed",
                    leaf_type: "Needle",
                    leaf_arrangement:"none",
                    leaf_shape:"none",
                    needle_shape: "Flat",
                    cone_type: "Woody",
                    fruit: "Cone",
                    min_elevation: 7900,
                    max_elevation: 10200,
                    min_height: 60,
                    max_height: 125,
                    twig_texture: "Smooth",
                    flower_shape:"none",
                    flower_color:"none",
                    habitat: "montane",
                    leaf_picture: "imgcat ./lib/pic/White-Fir-leaftall-225x300.jpg",
                    tree_picture: "imgcat ./lib/pic/White-Fir-tree.jpg" 
                 )    
  